language: cpp
compiler:
  - g++
os:
  - linux

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8 cmake git
- git clone git@github.com:acampoh/source.git lede
- cd lede && make
- export CXX="g++-4.8"
script: "cmake . && make"
